# Analysing datasets

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

# from librep.datasets.har.loaders import PandasMultiModalLoader
# from librep.utils.dataset import PandasDatasetsIO
# from librep.datasets.multimodal import PandasMultiModalDataset

In [2]:
import torch
import torch.nn as nn

pool = nn.MaxPool1d(2, stride=2, return_indices=True)
unpool = nn.MaxUnpool1d(2, stride=2)
input = torch.tensor([[[1., 2, 3, 4, 5, 6, 7, 8]]])
output, indices = pool(input)
print(output)
print(indices)
unpool(output, indices)

# Example showcasing the use of output_size
input = torch.tensor([[[1., 2, 3, 4, 5, 6, 7, 8, 9]]])
output, indices = pool(input)
unpool(output, indices, output_size=input.size())

unpool(output, indices)

tensor([[[2., 4., 6., 8.]]])
tensor([[[1, 3, 5, 7]]])


tensor([[[0., 2., 0., 4., 0., 6., 0., 8.]]])